import {
  AlignLeft,
  ChartBar,
  Cube,
  Buildings,
  Calendar,
  CalendarCheck,
  CalendarDots,
  CalendarPlus,
  CheckSquare,
  RadioButton,
  Clock,
  CreditCard,
  CurrencyDollar,
  FileText,
  Function,
  Hash,
  Image,
  Link,
  List,
  ListChecks,
  ListNumbers,
  Envelope,
  ChatCircle,
  Palette,
  Paperclip,
  Percent,
  Phone,
  MagnifyingGlass,
  Sigma,
  Star,
  Tag,
  Target,
  ToggleLeft,
  TrendUp,
  TextT,
  User,
  UserPlus,
  Wallet,
  Stack,
} from "@phosphor-icons/react";
import type { Icon } from "@phosphor-icons/react";

const ICON_MAP: Record<string, Icon> = {
  AlignLeft,
  BarChart2: ChartBar,
  Box: Cube,
  Building2: Buildings,
  Calendar,
  CalendarCheck,
  CalendarClock: CalendarDots,
  CalendarPlus,
  CheckSquare,
  CircleDot: RadioButton,
  Clock,
  CreditCard,
  DollarSign: CurrencyDollar,
  FileText,
  FunctionSquare: Function,
  Hash,
  Image,
  Link,
  Link2: Link,
  List,
  ListChecks,
  ListOrdered: ListNumbers,
  Mail: Envelope,
  MessageCircle: ChatCircle,
  Palette,
  Paperclip,
  Percent,
  Phone,
  Search: MagnifyingGlass,
  Sigma,
  Star,
  Tag,
  Target,
  ToggleLeft,
  TrendingUp: TrendUp,
  Type: TextT,
  User,
  UserPlus,
  Wallet,
  Layers: Stack,
};

export function getIcon(name: string): Icon {
  return ICON_MAP[name] ?? Cube;
}
