// ============================================================
// Seed: Daily brief — LLM summary via Ollama, stored in Inbox
// ============================================================

import type { AutomationConfig } from "../types/index.js";

export interface DailyBriefLlmParams {
  readonly id: string;
  /** Cron expression, default: every day at 8am */
  readonly cronExpression?: string;
  readonly timezone?: string;
  /** Ollama model name, default: llama3 */
  readonly model?: string;
}

/**
 * Creates a ROUTINE automation that runs daily at 8am,
 * prompts Ollama with today's context, and creates a brief in Inbox.
 * Falls back to a static template if LLM is unavailable.
 */
export function createDailyBriefLlmRoutine(params: DailyBriefLlmParams): AutomationConfig {
  const model = params.model ?? "llama3";
  return {
    id: params.id,
    kind: "ROUTINE",
    name: "Daily brief (LLM)",
    description: "Generates a daily brief using Ollama and stores it in Inbox",
    enabled: true,
    trigger: {
      type: "cron",
      expression: params.cronExpression ?? "0 8 * * *",
      timezone: params.timezone,
    },
    actions: [
      {
        type: "llm-prompt",
        model,
        prompt: [
          "You are a personal assistant for Supernote.",
          "Today is {{now}}.",
          "Generate a concise daily brief summarizing:",
          "- Key tasks and projects due today",
          "- Contacts with upcoming birthdays or meetings",
          "- Any important notes created yesterday",
          "Keep it under 200 words, use bullet points.",
          "If you don't have specific data, provide a helpful template.",
        ].join("\n"),
        storeResultAs: "dailyBrief",
      },
      {
        type: "create-inbox-note",
        title: "Daily Brief — {{now}}",
        body: "{{trigger.dailyBrief}}\n\n---\n_Generated by Daily Brief routine_",
        tags: ["daily-brief", "routine"],
      },
      {
        type: "notify-app",
        title: "Daily brief ready",
        body: "Your daily brief has been added to Inbox.",
        level: "info",
      },
    ],
  };
}
