import type { EntityTypeDefinition } from "./types.js";

export const accountSeed: EntityTypeDefinition = {
  name: "Account",
  pluralName: "Accounts",
  plural: "Accounts",
  icon: "wallet",
  color: "#4F8EF7",
  defaultPath: "/Finance/Accounts",
  fileNamePattern: "{name}",
  fields: [
    {
      id: "account_name",
      name: "name",
      label: "Account name",
      kind: "text",
      required: true,
      unique: false,
    },
    {
      id: "account_kind",
      name: "kind",
      label: "Type",
      kind: "select",
      required: true,
      unique: false,
      options: [
        { value: "checking", label: "Checking", color: "#60A5FA" },
        { value: "savings", label: "Savings", color: "#34D399" },
        { value: "livret", label: "Livret", color: "#A78BFA" },
        { value: "pea", label: "PEA", color: "#FBBF24" },
        { value: "cto", label: "CTO", color: "#F97316" },
        { value: "assurance_vie", label: "Assurance-vie", color: "#EC4899" },
        { value: "crypto", label: "Crypto wallet", color: "#F59E0B" },
        { value: "other", label: "Other", color: "#94A3B8" },
      ],
    },
    {
      id: "account_institution",
      name: "institution",
      label: "Institution",
      kind: "relation",
      required: false,
      unique: false,
      targetTypeId: "Organisation",
      cardinality: "many_to_many",
    },
    {
      id: "account_currency",
      name: "currency",
      label: "Currency",
      kind: "select",
      required: true,
      unique: false,
      defaultValue: "EUR",
      options: [
        { value: "EUR", label: "EUR" },
        { value: "USD", label: "USD" },
        { value: "CHF", label: "CHF" },
        { value: "GBP", label: "GBP" },
        { value: "BTC", label: "BTC" },
        { value: "ETH", label: "ETH" },
      ],
    },
    {
      id: "account_iban",
      name: "iban",
      label: "IBAN",
      kind: "text",
      required: false,
      unique: false,
    },
    {
      id: "account_current_balance",
      name: "current_balance",
      label: "Current balance",
      kind: "currency",
      required: false,
      unique: false,
      precision: 2,
    },
    {
      id: "account_last_synced_at",
      name: "last_synced_at",
      label: "Last synced at",
      kind: "datetime",
      required: false,
      unique: false,
    },
    {
      id: "account_created_at",
      name: "createdAt",
      label: "Created at",
      kind: "createdAt",
      required: false,
      unique: false,
    },
    {
      id: "account_updated_at",
      name: "updatedAt",
      label: "Updated at",
      kind: "updatedAt",
      required: false,
      unique: false,
    },
  ],
};
