import type { EntityTypeDefinition } from "./types.js";

export const assetSeed: EntityTypeDefinition = {
  name: "Asset",
  pluralName: "Assets",
  plural: "Assets",
  icon: "trending-up",
  color: "#10B981",
  defaultPath: "/Finance/Assets",
  fileNamePattern: "{name}",
  defaultView: "kanban",
  fields: [
    {
      id: "asset_name",
      name: "name",
      label: "Asset name",
      kind: "text",
      required: true,
      unique: false,
    },
    {
      id: "asset_category",
      name: "category",
      label: "Category",
      kind: "select",
      required: true,
      unique: false,
      options: [
        { value: "real_estate", label: "Real estate", color: "#7C3AED" },
        { value: "stock", label: "Stock", color: "#2563EB" },
        { value: "crypto", label: "Crypto", color: "#D97706" },
        { value: "bond", label: "Bond", color: "#059669" },
        { value: "fund", label: "Fund", color: "#0891B2" },
        { value: "cash", label: "Cash", color: "#16A34A" },
        { value: "other", label: "Other", color: "#64748B" },
      ],
    },
    {
      id: "asset_acquisition_date",
      name: "acquisition_date",
      label: "Acquisition date",
      kind: "date",
      required: false,
      unique: false,
    },
    {
      id: "asset_acquisition_value",
      name: "acquisition_value",
      label: "Acquisition value",
      kind: "currency",
      required: false,
      unique: false,
      precision: 2,
    },
    {
      id: "asset_current_value",
      name: "current_value",
      label: "Current value",
      kind: "currency",
      required: false,
      unique: false,
      precision: 2,
    },
    {
      id: "asset_account",
      name: "account",
      label: "Account",
      kind: "relation",
      required: false,
      unique: false,
      targetTypeId: "Account",
      cardinality: "many_to_many",
    },
    // Real estate specific
    {
      id: "asset_address",
      name: "address",
      label: "Address",
      kind: "longtext",
      required: false,
      unique: false,
      group: "real_estate",
    },
    {
      id: "asset_surface_sqm",
      name: "surface_sqm",
      label: "Surface (m²)",
      kind: "number",
      required: false,
      unique: false,
      precision: 1,
      group: "real_estate",
    },
    {
      id: "asset_loan",
      name: "loan",
      label: "Loan",
      kind: "relation",
      required: false,
      unique: false,
      targetTypeId: "Loan",
      cardinality: "many_to_many",
      group: "real_estate",
    },
    {
      id: "asset_valuation_method",
      name: "valuation_method",
      label: "Valuation method",
      kind: "select",
      required: false,
      unique: false,
      group: "real_estate",
      options: [
        { value: "manual", label: "Manual" },
        { value: "index", label: "Index" },
        { value: "expert", label: "Expert appraisal" },
      ],
    },
    {
      id: "asset_last_valuation_at",
      name: "last_valuation_at",
      label: "Last valuation at",
      kind: "datetime",
      required: false,
      unique: false,
      group: "real_estate",
    },
    // Stock specific
    {
      id: "asset_ticker",
      name: "ticker",
      label: "Ticker",
      kind: "text",
      required: false,
      unique: false,
      helpText: "e.g. AAPL, MC.PA",
      group: "stock",
    },
    {
      id: "asset_shares",
      name: "shares",
      label: "Shares",
      kind: "number",
      required: false,
      unique: false,
      precision: 6,
      group: "stock",
    },
    {
      id: "asset_currency",
      name: "currency",
      label: "Currency",
      kind: "select",
      required: false,
      unique: false,
      group: "stock",
      options: [
        { value: "EUR", label: "EUR" },
        { value: "USD", label: "USD" },
        { value: "CHF", label: "CHF" },
        { value: "GBP", label: "GBP" },
      ],
    },
    // Crypto specific
    {
      id: "asset_symbol",
      name: "symbol",
      label: "Symbol",
      kind: "text",
      required: false,
      unique: false,
      helpText: "e.g. BTC, ETH",
      group: "crypto",
    },
    {
      id: "asset_quantity",
      name: "quantity",
      label: "Quantity",
      kind: "number",
      required: false,
      unique: false,
      precision: 8,
      group: "crypto",
    },
    // Bond / fund specific
    {
      id: "asset_isin",
      name: "isin",
      label: "ISIN",
      kind: "text",
      required: false,
      unique: false,
      group: "bond_fund",
    },
    {
      id: "asset_units",
      name: "units",
      label: "Units",
      kind: "number",
      required: false,
      unique: false,
      precision: 6,
      group: "bond_fund",
    },
    {
      id: "asset_created_at",
      name: "createdAt",
      label: "Created at",
      kind: "createdAt",
      required: false,
      unique: false,
    },
    {
      id: "asset_updated_at",
      name: "updatedAt",
      label: "Updated at",
      kind: "updatedAt",
      required: false,
      unique: false,
    },
  ],
};
