import type { EntityTypeDefinition } from "./types.js";

export const goalSeed: EntityTypeDefinition = {
  name: "Goal",
  pluralName: "Goals",
  plural: "Goals",
  icon: "target",
  color: "#F59E0B",
  defaultPath: "/Finance/Goals",
  fileNamePattern: "{name}",
  fields: [
    {
      id: "goal_name",
      name: "name",
      label: "Goal name",
      kind: "text",
      required: true,
      unique: false,
    },
    {
      id: "goal_target_amount",
      name: "target_amount",
      label: "Target amount",
      kind: "currency",
      required: true,
      unique: false,
      precision: 2,
    },
    {
      id: "goal_target_date",
      name: "target_date",
      label: "Target date",
      kind: "date",
      required: false,
      unique: false,
    },
    {
      id: "goal_category",
      name: "category",
      label: "Category",
      kind: "select",
      required: false,
      unique: false,
      options: [
        { value: "savings", label: "Savings", color: "#16A34A" },
        { value: "investment", label: "Investment", color: "#2563EB" },
        { value: "debt", label: "Debt repayment", color: "#EF4444" },
        { value: "patrimony", label: "Patrimony growth", color: "#7C3AED" },
      ],
    },
    {
      id: "goal_current_progress",
      name: "current_progress",
      label: "Current progress",
      kind: "formula",
      required: false,
      unique: false,
      expression: "sumRelated('Asset', 'current_value')",
      outputKind: "currency",
      helpText: "Formula-computed from linked assets",
    },
    {
      id: "goal_description",
      name: "description",
      label: "Description",
      kind: "longtext",
      required: false,
      unique: false,
    },
    {
      id: "goal_created_at",
      name: "createdAt",
      label: "Created at",
      kind: "createdAt",
      required: false,
      unique: false,
    },
    {
      id: "goal_updated_at",
      name: "updatedAt",
      label: "Updated at",
      kind: "updatedAt",
      required: false,
      unique: false,
    },
  ],
};
