import type { EntityTypeDefinition } from "./types.js";

export const loanSeed: EntityTypeDefinition = {
  name: "Loan",
  pluralName: "Loans",
  plural: "Loans",
  icon: "landmark",
  color: "#EF4444",
  defaultPath: "/Finance/Loans",
  fileNamePattern: "{name}",
  defaultView: "table",
  fields: [
    {
      id: "loan_name",
      name: "name",
      label: "Loan name",
      kind: "text",
      required: true,
      unique: false,
    },
    {
      id: "loan_principal",
      name: "principal",
      label: "Principal",
      kind: "currency",
      required: true,
      unique: false,
      precision: 2,
    },
    {
      id: "loan_rate_annual",
      name: "rate_annual",
      label: "Annual rate",
      kind: "percent",
      required: true,
      unique: false,
      precision: 4,
      helpText: "e.g. 0.0344 for 3.44%",
    },
    {
      id: "loan_term_months",
      name: "term_months",
      label: "Term (months)",
      kind: "number",
      required: true,
      unique: false,
    },
    {
      id: "loan_start_date",
      name: "start_date",
      label: "Start date",
      kind: "date",
      required: true,
      unique: false,
    },
    {
      id: "loan_monthly_payment",
      name: "monthly_payment",
      label: "Monthly payment",
      kind: "formula",
      required: false,
      unique: false,
      expression: "computeMonthlyPayment(principal, rate_annual, term_months)",
      outputKind: "currency",
    },
    {
      id: "loan_remaining_principal",
      name: "remaining_principal",
      label: "Remaining principal",
      kind: "formula",
      required: false,
      unique: false,
      expression: "computeRemainingPrincipal(principal, rate_annual, term_months, start_date, today())",
      outputKind: "currency",
    },
    {
      id: "loan_end_date",
      name: "end_date",
      label: "End date",
      kind: "formula",
      required: false,
      unique: false,
      expression: "dateAdd(start_date, term_months, 'months')",
      outputKind: "date",
    },
    {
      id: "loan_kind",
      name: "kind",
      label: "Loan type",
      kind: "select",
      required: false,
      unique: false,
      options: [
        { value: "mortgage", label: "Mortgage", color: "#7C3AED" },
        { value: "consumer", label: "Consumer", color: "#2563EB" },
        { value: "personal", label: "Personal", color: "#059669" },
        { value: "auto", label: "Auto", color: "#D97706" },
        { value: "student", label: "Student", color: "#0891B2" },
        { value: "other", label: "Other", color: "#64748B" },
      ],
    },
    {
      id: "loan_lender",
      name: "lender",
      label: "Lender",
      kind: "relation",
      required: false,
      unique: false,
      targetTypeId: "Organisation",
      cardinality: "many_to_many",
    },
    {
      id: "loan_created_at",
      name: "createdAt",
      label: "Created at",
      kind: "createdAt",
      required: false,
      unique: false,
    },
    {
      id: "loan_updated_at",
      name: "updatedAt",
      label: "Updated at",
      kind: "updatedAt",
      required: false,
      unique: false,
    },
  ],
};
