import type { EntityTypeDefinition } from "./types.js";

export const snapshotSeed: EntityTypeDefinition = {
  name: "Snapshot",
  pluralName: "Snapshots",
  plural: "Snapshots",
  icon: "camera",
  color: "#8B5CF6",
  defaultPath: "/Finance/Snapshots",
  fileNamePattern: "{name}-{taken_at}",
  fields: [
    {
      id: "snapshot_name",
      name: "name",
      label: "Snapshot name",
      kind: "text",
      required: true,
      unique: false,
    },
    {
      id: "snapshot_taken_at",
      name: "taken_at",
      label: "Taken at",
      kind: "datetime",
      required: true,
      unique: false,
    },
    {
      id: "snapshot_total_net_worth",
      name: "total_net_worth",
      label: "Total net worth",
      kind: "currency",
      required: false,
      unique: false,
      precision: 2,
      helpText: "Frozen value at snapshot time",
    },
    {
      id: "snapshot_breakdown",
      name: "breakdown",
      label: "Breakdown",
      kind: "longtext",
      required: false,
      unique: false,
      helpText: "JSON breakdown by category",
    },
    {
      id: "snapshot_notes",
      name: "notes",
      label: "Notes",
      kind: "longtext",
      required: false,
      unique: false,
    },
    {
      id: "snapshot_created_at",
      name: "createdAt",
      label: "Created at",
      kind: "createdAt",
      required: false,
      unique: false,
    },
    {
      id: "snapshot_updated_at",
      name: "updatedAt",
      label: "Updated at",
      kind: "updatedAt",
      required: false,
      unique: false,
    },
  ],
};
