/**
 * Curated icon re-exports from lucide-react.
 *
 * Use these named exports instead of importing from lucide-react directly.
 * This indirection allows swapping the icon library in the future without
 * touching the rest of the codebase.
 *
 * Naming convention: Icon + PascalCase concept.
 */
export {
  // Navigation / UI chrome
  Home as IconHome,
  Search as IconSearch,
  Settings as IconSettings,
  Menu as IconMenu,
  X as IconClose,
  ChevronDown as IconChevronDown,
  ChevronUp as IconChevronUp,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  ArrowLeft as IconArrowLeft,
  ArrowRight as IconArrowRight,
  ArrowUp as IconArrowUp,
  ArrowDown as IconArrowDown,
  PanelLeft as IconPanelLeft,
  PanelRight as IconPanelRight,
  PanelLeftClose as IconPanelLeftClose,
  SidebarOpen as IconSidebarOpen,
  LayoutDashboard as IconDashboard,
  Columns2 as IconColumns,
  Rows3 as IconRows,
  Grid2x2 as IconGrid,
  List as IconList,
  Kanban as IconKanban,
  Calendar as IconCalendar,
  CalendarRange as IconTimeline,
  Map as IconMap,
  Network as IconGraph,

  // Content / Entities
  FileText as IconNote,
  FileCode as IconCode,
  File as IconFile,
  Folder as IconFolder,
  FolderOpen as IconFolderOpen,
  Hash as IconTag,
  Bookmark as IconBookmark,
  BookOpen as IconLibrary,
  Inbox as IconInbox,
  Star as IconStar,
  Heart as IconHeart,
  Flag as IconFlag,
  Archive as IconArchive,
  Trash2 as IconTrash,
  Trash as IconTrashAlt,

  // CRM / People
  User as IconUser,
  Users as IconUsers,
  UserPlus as IconUserPlus,
  UserCheck as IconUserCheck,
  Building2 as IconOrganisation,
  Briefcase as IconProject,
  Phone as IconPhone,
  Mail as IconMail,
  Globe as IconWebsite,
  Linkedin as IconLinkedIn,
  Twitter as IconTwitter,
  Github as IconGithub,
  MessageSquare as IconMessage,
  MessageCircle as IconChat,

  // Actions
  Plus as IconPlus,
  Minus as IconMinus,
  Edit3 as IconEdit,
  Pencil as IconPencil,
  Copy as IconCopy,
  Clipboard as IconClipboard,
  ClipboardCheck as IconClipboardCheck,
  Scissors as IconScissors,
  Link as IconLink,
  Link2 as IconLink2,
  Unlink as IconUnlink,
  ExternalLink as IconExternalLink,
  Download as IconDownload,
  Upload as IconUpload,
  Share2 as IconShare,
  RefreshCw as IconRefresh,
  RotateCcw as IconUndo,
  RotateCw as IconRedo,
  Save as IconSave,
  Send as IconSend,

  // Status / Feedback
  Check as IconCheck,
  CheckCircle2 as IconCheckCircle,
  XCircle as IconXCircle,
  AlertCircle as IconAlertCircle,
  AlertTriangle as IconAlertTriangle,
  Info as IconInfo,
  HelpCircle as IconHelp,
  Loader2 as IconLoader,
  Clock as IconClock,
  Timer as IconTimer,
  CalendarCheck2 as IconCalendarCheck,
  CalendarX2 as IconCalendarX,

  // Media / Assets
  Image as IconImage,
  Video as IconVideo,
  Music as IconMusic,
  Mic as IconMic,
  Camera as IconCamera,
  Paperclip as IconAttachment,

  // Data / Schema
  Database as IconDatabase,
  Table as IconTable,
  Layers as IconLayers,
  GitBranch as IconGitBranch,
  GitCommit as IconGitCommit,
  GitMerge as IconGitMerge,
  Workflow as IconWorkflow,
  Zap as IconAutomation,
  Bot as IconAI,
  Cpu as IconProcessing,
  HardDrive as IconDisk,
  ServerCog as IconServer,

  // UI / Layout
  Eye as IconEye,
  EyeOff as IconEyeOff,
  Lock as IconLock,
  Unlock as IconUnlock,
  Key as IconKey,
  Shield as IconShield,
  Bell as IconBell,
  BellOff as IconBellOff,
  Sun as IconSun,
  Moon as IconMoon,
  Monitor as IconMonitor,
  Maximize2 as IconMaximize,
  Minimize2 as IconMinimize,
  Move as IconMove,
  GripVertical as IconDragHandle,
  MoreHorizontal as IconMoreHorizontal,
  MoreVertical as IconMoreVertical,
  Filter as IconFilter,
  SortAsc as IconSortAsc,
  SortDesc as IconSortDesc,
  Sliders as IconSliders,

  // Finance
  DollarSign as IconCurrency,
  TrendingUp as IconTrendingUp,
  TrendingDown as IconTrendingDown,
  PieChart as IconPieChart,
  BarChart3 as IconBarChart,
  LineChart as IconLineChart,
  Wallet as IconWallet,
  CreditCard as IconCreditCard,
  Landmark as IconBank,
  Bitcoin as IconCrypto,
  Goal as IconGoal,
} from "lucide-react";

// Re-export the base type for icon component props
export type { LucideProps as IconProps, LucideIcon as IconComponent } from "lucide-react";
