/**
 * Curated icon re-exports from @phosphor-icons/react.
 *
 * Use these named exports instead of importing from @phosphor-icons/react directly.
 * This indirection allows swapping the icon library in the future without
 * touching the rest of the codebase.
 *
 * Naming convention: Icon + PascalCase concept.
 */
export {
  // Navigation / UI chrome
  House as IconHome,
  MagnifyingGlass as IconSearch,
  Gear as IconSettings,
  List as IconMenu,
  X as IconClose,
  CaretDown as IconChevronDown,
  CaretUp as IconChevronUp,
  CaretLeft as IconChevronLeft,
  CaretRight as IconChevronRight,
  ArrowLeft as IconArrowLeft,
  ArrowRight as IconArrowRight,
  ArrowUp as IconArrowUp,
  ArrowDown as IconArrowDown,
  SidebarSimple as IconPanelLeft,
  SidebarSimple as IconPanelRight,
  SidebarSimple as IconPanelLeftClose,
  SidebarSimple as IconSidebarOpen,
  SquaresFour as IconDashboard,
  Columns as IconColumns,
  Rows as IconRows,
  GridFour as IconGrid,
  List as IconList,
  Kanban as IconKanban,
  Calendar as IconCalendar,
  CalendarDots as IconTimeline,
  MapTrifold as IconMap,
  Graph as IconGraph,

  // Content / Entities
  FileText as IconNote,
  FileCode as IconCode,
  File as IconFile,
  Folder as IconFolder,
  FolderOpen as IconFolderOpen,
  Hash as IconTag,
  Bookmark as IconBookmark,
  BookOpen as IconLibrary,
  Tray as IconInbox,
  Star as IconStar,
  Heart as IconHeart,
  Flag as IconFlag,
  Archive as IconArchive,
  Trash as IconTrash,
  Trash as IconTrashAlt,

  // CRM / People
  User as IconUser,
  Users as IconUsers,
  UserPlus as IconUserPlus,
  UserCircleCheck as IconUserCheck,
  Buildings as IconOrganisation,
  Briefcase as IconProject,
  Phone as IconPhone,
  Envelope as IconMail,
  Globe as IconWebsite,
  LinkedinLogo as IconLinkedIn,
  TwitterLogo as IconTwitter,
  GithubLogo as IconGithub,
  ChatText as IconMessage,
  ChatCircle as IconChat,

  // Actions
  Plus as IconPlus,
  Minus as IconMinus,
  PencilSimple as IconEdit,
  Pencil as IconPencil,
  Copy as IconCopy,
  Clipboard as IconClipboard,
  ClipboardText as IconClipboardCheck,
  Scissors as IconScissors,
  Link as IconLink,
  Link as IconLink2,
  LinkBreak as IconUnlink,
  ArrowSquareOut as IconExternalLink,
  DownloadSimple as IconDownload,
  UploadSimple as IconUpload,
  ShareNetwork as IconShare,
  ArrowsClockwise as IconRefresh,
  ArrowCounterClockwise as IconUndo,
  ArrowClockwise as IconRedo,
  FloppyDisk as IconSave,
  PaperPlaneTilt as IconSend,

  // Status / Feedback
  Check as IconCheck,
  CheckCircle as IconCheckCircle,
  XCircle as IconXCircle,
  WarningCircle as IconAlertCircle,
  Warning as IconAlertTriangle,
  Info as IconInfo,
  Question as IconHelp,
  Spinner as IconLoader,
  Clock as IconClock,
  Timer as IconTimer,
  CalendarCheck as IconCalendarCheck,
  CalendarX as IconCalendarX,

  // Media / Assets
  Image as IconImage,
  VideoCamera as IconVideo,
  MusicNote as IconMusic,
  Microphone as IconMic,
  Camera as IconCamera,
  Paperclip as IconAttachment,

  // Data / Schema
  Database as IconDatabase,
  Table as IconTable,
  Stack as IconLayers,
  GitBranch as IconGitBranch,
  GitCommit as IconGitCommit,
  GitMerge as IconGitMerge,
  Graph as IconWorkflow,
  Lightning as IconAutomation,
  Robot as IconAI,
  Cpu as IconProcessing,
  HardDrive as IconDisk,
  HardDrives as IconServer,

  // UI / Layout
  Eye as IconEye,
  EyeSlash as IconEyeOff,
  Lock as IconLock,
  LockOpen as IconUnlock,
  Key as IconKey,
  Shield as IconShield,
  Bell as IconBell,
  BellSlash as IconBellOff,
  Sun as IconSun,
  Moon as IconMoon,
  Monitor as IconMonitor,
  ArrowsOut as IconMaximize,
  ArrowsIn as IconMinimize,
  ArrowsOutCardinal as IconMove,
  DotsSixVertical as IconDragHandle,
  DotsThree as IconMoreHorizontal,
  DotsThreeVertical as IconMoreVertical,
  Funnel as IconFilter,
  SortAscending as IconSortAsc,
  SortDescending as IconSortDesc,
  Sliders as IconSliders,

  // Finance
  CurrencyDollar as IconCurrency,
  TrendUp as IconTrendingUp,
  TrendDown as IconTrendingDown,
  ChartPie as IconPieChart,
  ChartBar as IconBarChart,
  ChartLine as IconLineChart,
  Wallet as IconWallet,
  CreditCard as IconCreditCard,
  Bank as IconBank,
  Coins as IconCrypto,
  Target as IconGoal,
} from "@phosphor-icons/react";

// Re-export the base type for icon component props
export type { Icon as IconComponent, IconProps } from "@phosphor-icons/react";
