"use client";

/**
 * useCreateInboxNote — manages lifecycle of a note being composed in WritingSurface.
 *
 * Persistence flow:
 *   - First save: create entity via `entities.create` with typeId="note", filePath in Inbox/.
 *   - Subsequent saves: update entity via `entities.update` with new body.
 *   - Auto-save: 5s debounce while the user is typing (silent, no toast).
 *   - Manual save (Cmd+S): immediate save with success toast.
 *   - Initial creation: triggered on first blur or after 2s of inactivity.
 *
 * File naming: delegated to main process via EntityType.fileNamePattern.
 * Fields include `title` derived from first line.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { trpc } from "@/lib/trpc/client";
import {
  isAutoTitleEnabled,
  isDefaultTitle,
  useAutoTitle,
} from "./useAutoTitle";

export interface NoteState {
  entityId: string | null;
  isSaving: boolean;
  lastSaved: Date | null;
  saveError: string | null;
}

export interface UseCreateInboxNoteReturn extends NoteState {
  saveNote: (content: string) => void;
  onContentChange: (content: string) => void;
  resetNote: () => void;
  /** True if the most recent title was generated by Ollama (UI badge hint). */
  titleWasAiGenerated: boolean;
}

const NOTE_TYPE_ID = "note";
// 2.5s (was 5s): the previous window left up to 5s of typing unsaved on an
// accidental refresh / tab close. The visibility-flush below catches the
// tab-switch case, the shorter debounce shrinks the crash window.
const AUTO_SAVE_DELAY_MS = 2_500;
const INITIAL_CREATE_DELAY_MS = 2_000;
const AUTO_TITLE_DEBOUNCE_MS = 2_000;
const AUTO_TITLE_MIN_CHARS = 30;

function extractFirstLine(content: string): string {
  return content.split("\n").find((l) => l.trim().length > 0)?.trim() ?? "";
}

export function useCreateInboxNote(): UseCreateInboxNoteReturn {
  const [entityId, setEntityId] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [titleWasAiGenerated, setTitleWasAiGenerated] = useState(false);

  const entityIdRef = useRef<string | null>(null);
  const contentRef = useRef<string>("");
  const titleRef = useRef<string>("");
  const autoSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const initialCreateTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const autoTitleTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const utils = trpc.useUtils();
  const { suggest: suggestTitle, isAvailable: ollamaAvailable } = useAutoTitle();

  const createMutation = trpc.entities.create.useMutation({
    onSuccess: (entity) => {
      setEntityId(entity.id);
      entityIdRef.current = entity.id;
      const createdTitle =
        typeof entity.fields["title"] === "string"
          ? (entity.fields["title"] as string)
          : "";
      titleRef.current = createdTitle;
      setIsSaving(false);
      setLastSaved(new Date());
      setSaveError(null);
      // Refresh notes list & search so the new note appears immediately in /notes
      void utils.entities.list.invalidate({ typeId: NOTE_TYPE_ID });
      void utils.entities.search.invalidate();
    },
    onError: (err) => {
      setIsSaving(false);
      setSaveError(err.message);
    },
  });

  const updateMutation = trpc.entities.update.useMutation({
    onSuccess: (entity) => {
      setIsSaving(false);
      setLastSaved(new Date());
      setSaveError(null);
      // Reflect updated title/body in lists & detail view
      void utils.entities.get.invalidate({ id: entity.id });
      void utils.entities.list.invalidate({ typeId: NOTE_TYPE_ID });
      void utils.entities.search.invalidate();
    },
    onError: (err) => {
      setIsSaving(false);
      setSaveError(err.message);
    },
  });

  const persist = useCallback(
    (content: string) => {
      if (!content.trim()) return;
      setIsSaving(true);

      if (entityIdRef.current) {
        updateMutation.mutate({ id: entityIdRef.current, body: content });
      } else {
        const title = extractFirstLine(content);
        titleRef.current = title;
        createMutation.mutate({
          typeId: NOTE_TYPE_ID,
          fields: { title },
          body: content,
        });
      }
    },
    [createMutation, updateMutation],
  );

  /**
   * Schedule an auto-title suggestion. Fires 2s after the user stops typing,
   * only if Ollama is reachable, the toggle is on, the body is long enough,
   * and the current title still looks like a placeholder.
   *
   * No-op (silent) on any failure — never blocks saving.
   */
  const scheduleAutoTitle = useCallback(
    (content: string) => {
      if (!ollamaAvailable) return;
      if (!isAutoTitleEnabled()) return;
      if (content.trim().length < AUTO_TITLE_MIN_CHARS) return;
      if (!isDefaultTitle(titleRef.current)) return;

      if (autoTitleTimer.current) clearTimeout(autoTitleTimer.current);
      autoTitleTimer.current = setTimeout(async () => {
        const id = entityIdRef.current;
        // Need an entity to update; auto-save will create one within 5s.
        if (!id) return;
        if (!isDefaultTitle(titleRef.current)) return;
        const suggested = await suggestTitle(content, titleRef.current);
        if (!suggested) return;
        if (!isDefaultTitle(titleRef.current)) return; // user typed in the meantime
        titleRef.current = suggested;
        setTitleWasAiGenerated(true);
        updateMutation.mutate({ id, fields: { title: suggested } });
      }, AUTO_TITLE_DEBOUNCE_MS);
    },
    [ollamaAvailable, suggestTitle, updateMutation],
  );

  const saveNote = useCallback(
    (content: string) => {
      contentRef.current = content;
      if (autoSaveTimer.current) {
        clearTimeout(autoSaveTimer.current);
        autoSaveTimer.current = null;
      }
      persist(content);
    },
    [persist],
  );

  const onContentChange = useCallback(
    (content: string) => {
      contentRef.current = content;

      // Schedule initial entity creation after short inactivity
      if (!entityIdRef.current) {
        if (initialCreateTimer.current) clearTimeout(initialCreateTimer.current);
        initialCreateTimer.current = setTimeout(() => {
          // Null the ref so the visibility-flush knows nothing is pending.
          initialCreateTimer.current = null;
          if (contentRef.current.trim()) persist(contentRef.current);
        }, INITIAL_CREATE_DELAY_MS);
      }

      // Schedule auto-save (debounced) during typing
      if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current);
      autoSaveTimer.current = setTimeout(() => {
        autoSaveTimer.current = null;
        if (contentRef.current.trim()) persist(contentRef.current);
      }, AUTO_SAVE_DELAY_MS);

      // Schedule auto-title 2s after typing stops (no-op if disabled / unavailable)
      scheduleAutoTitle(content);
    },
    [persist, scheduleAutoTitle],
  );

  const resetNote = useCallback(() => {
    if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current);
    if (initialCreateTimer.current) clearTimeout(initialCreateTimer.current);
    if (autoTitleTimer.current) clearTimeout(autoTitleTimer.current);
    contentRef.current = "";
    titleRef.current = "";
    entityIdRef.current = null;
    setEntityId(null);
    setIsSaving(false);
    setLastSaved(null);
    setSaveError(null);
    setTitleWasAiGenerated(false);
  }, []);

  useEffect(() => {
    return () => {
      if (autoSaveTimer.current) clearTimeout(autoSaveTimer.current);
      if (initialCreateTimer.current) clearTimeout(initialCreateTimer.current);
      if (autoTitleTimer.current) clearTimeout(autoTitleTimer.current);
    };
  }, []);

  // Flush pending writes when the tab goes hidden or the page unloads —
  // the home WritingSurface is exactly where the user types a quick thought
  // and immediately switches away, which used to lose the debounce window.
  useEffect(() => {
    const flush = () => {
      const pending =
        autoSaveTimer.current !== null || initialCreateTimer.current !== null;
      if (!pending || !contentRef.current.trim()) return;
      if (autoSaveTimer.current) {
        clearTimeout(autoSaveTimer.current);
        autoSaveTimer.current = null;
      }
      if (initialCreateTimer.current) {
        clearTimeout(initialCreateTimer.current);
        initialCreateTimer.current = null;
      }
      persist(contentRef.current);
    };
    const onVisibilityChange = () => {
      if (document.visibilityState === "hidden") flush();
    };
    document.addEventListener("visibilitychange", onVisibilityChange);
    window.addEventListener("pagehide", flush);
    return () => {
      document.removeEventListener("visibilitychange", onVisibilityChange);
      window.removeEventListener("pagehide", flush);
    };
  }, [persist]);

  return {
    entityId,
    isSaving,
    lastSaved,
    saveError,
    saveNote,
    onContentChange,
    resetNote,
    titleWasAiGenerated,
  };
}
